export const ADD_FIREBASE_TO_STORE = 'ADD_FIREBASE_TO_STORE';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const GENERIC = 'GENERIC';
export const SEARCHING_RECIPES = 'SEARCHING_RECIPES';
export const SELECT_RECIPE_CARD = 'SELECT_RECIPE_CARD';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const TOGGLE_BOOLEAN = 'TOGGLE_BOOLEAN';
export const WIZARD_PAGE_NEXT = 'WIZARD_PAGE_NEXT';
export const WIZARD_PAGE_PREVIOUS = 'WIZARD_PAGE_PREVIOUS';

